name: CI Actions 🤖

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint-format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Run lint
        run: |
          yarn lint
      - name: Run prettier
        run: |
          yarn format
